import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import ts from 'typescript';
import typegpu from 'unplugin-typegpu';

const root = fileURLToPath(new URL('../', import.meta.url));
const sourcePath = join(root, 'vendor/shadercn/components/orbs/orb-31/gpu.ts');
const source = await readFile(sourcePath, 'utf8');
const registry = JSON.parse(await readFile(join(root, 'vendor/shadercn/orb-31.registry.json'), 'utf8'));
const original = registry.files.find(file => file.target === 'components/orbs/orb-31/gpu.ts');
if (!original || source !== original.content) throw new Error('ORB-31 source differs from the installed registry payload.');
const hash = createHash('sha256').update(source).digest('hex');
// Export the original function objects, not a hand-written approximation. The
// upstream module remains byte-for-byte intact; this adapter exists only in memory.
const adapter = source + '\nexport const sculptureGeometry = tgpu.resolve([smin.$name("orb31Smin"), coronaSDF.$name("orb31CoronaSDF")]);\n';
const plugin = typegpu.raw({}, { framework: 'rollup' });
const transformed = plugin.transform.handler.call({ warn(message) { throw new Error(String(message)); } }, adapter, sourcePath);
if (!transformed || typeof transformed.code !== 'string') throw new Error('TypeGPU did not compile ORB-31.');
const compiled = ts.transpileModule(transformed.code, {
  compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext },
  reportDiagnostics: true,
});
if (compiled.diagnostics?.some(diagnostic => diagnostic.category === ts.DiagnosticCategory.Error)) throw new Error('ORB-31 TypeScript transpilation failed.');
const cache = join(root, 'node_modules/.cache');
await mkdir(cache, { recursive: true });
const temporary = await mkdtemp(join(cache, 'orb31-'));
try {
  const modulePath = join(temporary, 'compiled.mjs');
  await writeFile(modulePath, compiled.outputText);
  const result = await import(pathToFileURL(modulePath).href);
  if (typeof result.sculptureGeometry !== 'string' || typeof result.orb31Shader !== 'string') throw new Error('ORB-31 compiler returned invalid WGSL.');
  const notice = `// Generated by scripts/compile-orb31.mjs from shadercn ORB-31.\n// Shader by XorDev (https://x.com/XorDev), ported for Orbkit with permission.\n// Non-commercial use only, with attribution to XorDev. Keep this notice.\n// Upstream source SHA-256: ${hash}\n`;
  await writeFile(join(root, 'src/shaders/vendor/orb31.wgsl'), notice + result.sculptureGeometry + '\n');
  await writeFile(join(root, 'vendor/shadercn/orb-31.wgsl'), notice + result.orb31Shader + '\n');
  console.log(`ORB-31: exact upstream geometry compiled (${hash}).`);
} finally {
  await rm(temporary, { recursive: true, force: true });
}
