import { createHash } from 'node:crypto';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import ts from 'typescript';
import typegpu from 'unplugin-typegpu';
const root=fileURLToPath(new URL('../',import.meta.url));
const output=join(root,'src/studio/orbs');
await mkdir(join(output,'shaders'),{recursive:true});
const plugin=typegpu.raw({}, {framework:'rollup'});
const catalog=[];
const cache=join(root,'node_modules/.cache');await mkdir(cache,{recursive:true});
const temporary=await mkdtemp(join(cache,'hyalos-orbs-'));
try {
 for(let i=1;i<=33;i++) {
  const id=`orb-${String(i).padStart(2,'0')}`,number=String(i).padStart(2,'0');
  const directory=join(root,'vendor/shadercn/components/orbs',id);
  const source=await readFile(join(directory,'gpu.ts'),'utf8');
  const registry=JSON.parse(await readFile(join(root,'vendor/shadercn/registry',`${id}.json`),'utf8'));
  if(source!==registry.files.find(f=>f.target.endsWith('/gpu.ts')).content) throw new Error(`${id}: source mismatch`);
  const transformed=plugin.transform.handler.call({warn(message){throw new Error(String(message));}},source,join(directory,'gpu.ts'));
  const gpuJS=ts.transpileModule(transformed.code,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
  const gpuPath=join(temporary,`${id}.mjs`);await writeFile(gpuPath,gpuJS);
  const meta=await readFile(join(directory,'meta.ts'),'utf8');
  const metaSource=meta.replaceAll(`@/components/orbs/${id}/gpu`,`./${id}.mjs`);
  const metaJS=ts.transpileModule(metaSource,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
  const metaPath=join(temporary,`${id}-meta.mjs`);await writeFile(metaPath,metaJS);
  const module=await import(pathToFileURL(metaPath).href);
  const variant=module[`orb${number}Orb`];
  if(!variant?.shader || !variant.uniforms) throw new Error(`${id}: missing shader or uniform schema`);
  const {shader,uniforms,...definition}=variant;
  const sourceHash=createHash('sha256').update(source).digest('hex');
  const schema=Object.fromEntries(Object.entries(uniforms.propTypes).map(([name,type])=>[name,type.type]));
  if(Object.values(schema).some(t=>!['f32','vec2f','vec3f','vec4f'].includes(t))) throw new Error(`${id}: unsupported uniform field`);
  catalog.push({...definition,schema,sourceHash});
  const notice=`// Compiled from unchanged shadercn ${id} using TypeGPU.\n// Shader by XorDev (https://x.com/XorDev), ported with permission.\n// Non-commercial use only, with attribution. Preserve this notice.\n// Source SHA-256: ${sourceHash}\n`;
  await writeFile(join(output,'shaders',`${id}.wgsl`),notice+shader+'\n');
  console.log(`${id}: ${shader.length} WGSL bytes; ${definition.params.length} controls`);
 }
 await writeFile(join(output,'catalog.ts'),`// Generated by scripts/compile-orbs.mjs from verified registry sources.\nimport type { OrbDefinition } from './types.ts';\nexport const ORB_CATALOG: readonly OrbDefinition[] = ${JSON.stringify(catalog,null,2)};\n`);
 await writeFile(join(output,'shaders.ts'),catalog.map((v,i)=>`import orb${i+1} from './shaders/${v.key}.wgsl?raw';`).join('\n')+`\nexport const ORB_SHADERS: Readonly<Record<string,string>> = {\n`+catalog.map((v,i)=>`  '${v.key}': orb${i+1},`).join('\n')+'\n};\n');
} finally { await rm(temporary,{recursive:true,force:true}); }
